apiVersion: skaffold/v3
kind: Config
build:
  artifacts:
    - image: stile95/userauth
      context: userauth
      sync:
        manual:
          - src: src/**/*.js
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: stile95/movies
      context: movies
      sync:
        manual:
          - src: src/**/*.js
            dest: .
          - src: src/html/*.html
            dest: src/html
      docker:
        dockerfile: Dockerfile
###
#    - image: stile95/movies-html
#      context: .
#      sync:
#        manual:
#          - src: src/html/**.html
#            dest: .
#      docker:
#        dockerfile: .
###
  local:
    push: false
manifests:
  rawYaml:
    - ./infrastructure/k8s/*
deploy:
  kubectl: {}