apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      initContainers:
        - name: wait-for-nats
          image: busybox
          command: ["sh", "-c", "until nc -z nats-srv:4222; do sleep 1; done"]
      containers:
        - name: expiration
          image: stile95/expiration:latest
          env:
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: REDIS_HOST
              value: "expiration-redis-srv"
