apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: vodapp.dev
      http:
        paths:
          - path: /users/.*
            pathType: ImplementationSpecific
            backend:
              service:
                name: userauth-srv
                port:
                  number: 3000
          - path: /movies/.*
            pathType: ImplementationSpecific
            backend:
              service:
                name: movies-srv
                port:
                  number: 3000
          - path: /recommendations/.*
            pathType: ImplementationSpecific
            backend:
              service:
                name: recommendation-srv
                port:
                  number: 3000