apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      labels:
        app: movies
    spec:
      initContainers:
        - name: wait-for-nats
          image: busybox
          command: ["sh", "-c", "until nc -z nats-srv:4222; do sleep 1; done"]
        - name: wait-for-mongo
          image: busybox
          command: ["sh", "-c", "until nc -z movies-mongo-srv:27017; do sleep 1; done"]
        - name: set-output-permissions
          image: busybox
          command: ["sh", "-c", "mkdir -p /app/src/output && chown -R 1000:1000 /app/src/output"]
          volumeMounts:
            - name: output-volume
              mountPath: /app/src/output  
      containers:
        - name: movies
          image: stile95/movies:latest
          env:
            - name: DATABASE_URL
              value: "mongodb://userauth-mongo-srv:27017/movies"
            - name: JWT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET_KEY
            - name: NATS_URL
              value: "http://nats-srv:4222"

          volumeMounts:
            - name: output-volume
              mountPath: /app/src/output
      volumes:
        - name: output-volume
          persistentVolumeClaim:
            claimName: movies-output-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: movies-srv
spec: ##default ClusterIP service
  selector:
    app: movies
  ports:
    - name: movies
      protocol: TCP
      port: 3000
      targetPort: 3000
