apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies-mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies-mongo
  template:
    metadata:
      labels:
        app: movies-mongo
    spec:
      initContainers:
        - name: remove-lockfile
          image: busybox
          command: ["sh", "-c", "rm -f /data/db/mongod.lock /data/db/WiredTiger.lock"]
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 999:999 /data/db && chmod -R u+rwX /data/db"]
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      containers:
        - image: mongo
          name: movies-mongo
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: movies-mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: movies-mongo-srv
spec:
  selector:
    app: movies-mongo
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
      targetPort: 27017