apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation
  template:
    metadata:
      labels:
        app: recommendation
    spec:
      initContainers:
        - name: wait-for-nats
          image: busybox
          command: ["sh", "-c", "until nc -z nats-srv:4222; do sleep 1; done"]
      containers:
        - name: recommendation
          image: stile95/recommendation
          env:
            - name: DATABASE_URL
              value: "mongodb://recommendation-mongo-srv:27017/"
            - name: JWT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET_KEY
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: OPEN_AI_API
            - name: DATABASE_NAME
              value: "VectorDB"
            - name: COLLECTION_NAME
              value: "movies"
            - name: MONGOATLAS_URL
              valueFrom:
                secretKeyRef:
                  name: mongo-url
                  key: MONGOURI
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-srv
spec:
  selector:
    app: recommendation
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
