apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-expiration-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscription-expiration
  template:
    metadata:
      labels:
        app: subscription-expiration
    spec:
      initContainers:
        - name: wait-for-nats
          image: busybox
          command: ["sh", "-c", "until nc -z nats-srv:4222; do sleep 1; done"]
        - name: wait-for-mongo
          image: busybox
          command: ["sh", "-c", "until nc -z subscription-expiration-mongo-srv:27017; do sleep 1; done"]
      containers:
        - name: subscription-expiration
          image: stile95/subscription-expiration:latest
          env:
            - name: DATABASE_URL
              value: "mongodb://subscription-expiration-mongo-srv:27017/subscription"
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: REDIS_HOST
              value: "subscription-expiration-redis-srv"
---
apiVersion: v1
kind: Service
metadata:
  name: subscription-srv
spec: ##default ClusterIP service
  selector:
    app: subscription
  ports:
    - name: subscription
      protocol: TCP
      port: 3000
      targetPort: 3000
