apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscription
  template:
    metadata:
      labels:
        app: subscription
    spec:
      initContainers:
        - name: wait-for-nats
          image: busybox
          command: ["sh", "-c", "until nc -z nats-srv:4222; do sleep 1; done"]
        - name: wait-for-mongo
          image: busybox
          command: ["sh", "-c", "until nc -z subscription-mongo-srv:27017; do sleep 1; done"]
      containers:
        - name: subscription
          image: stile95/subscription:latest
          env:
            - name: DATABASE_URL
              value: "mongodb://subscription-mongo-srv:27017/subscription"
            - name: JWT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET_KEY
            - name: NATS_URL
              value: "http://nats-srv:4222"
---
apiVersion: v1
kind: Service
metadata:
  name: subscription-srv
spec: ##default ClusterIP service
  selector:
    app: subscription
  ports:
    - name: subscription
      protocol: TCP
      port: 3000
      targetPort: 3000
