apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-expiration-mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscription-expiration-mongo
  template:
    metadata:
      labels:
        app: subscription-expiration-mongo
    spec:
      containers:
        - image: mongo
          name: subscription-expiration-mongo
---
apiVersion: v1
kind: Service
metadata:
  name: subscription-expiration-mongo-srv
spec:
  selector:
    app: subscription-expiration-mongo
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
      targetPort: 27017
