apiVersion: v1
kind: PersistentVolume
metadata:
  name: subscription-mongo-pv
  labels:
    app: subscription-mongo
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/subscription-mongo-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: subscription-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  selector:
    matchLabels:
      app: subscription-mongo