apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcode-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transcode-worker
  template:
    metadata:
      labels:
        app: transcode-worker
    spec:
      initContainers:
        - name: wait-for-mongo
          image: busybox
          command: ["sh", "-c", "until nc -z movies-mongo-srv:27017; do sleep 1; done"]
        - name: wait-for-redis
          image: busybox
          command: ["sh", "-c", "until nc -z transcode-redis-srv:6379; do sleep 1; done"]
        - name: set-permissions
          image: busybox
          command: ["sh", "-c", "mkdir -p /app/src/output && chown -R 1000:1000 /app/src/output"]
          volumeMounts:
            - name: output-volume
              mountPath: /app/src/output
      containers:
        - name: transcode-worker
          image: stile95/transcode-worker:latest
          env:
            - name: DATABASE_URL
              value: "mongodb://movies-mongo-srv:27017/movies"
            - name: REDIS_URL
              value: "redis://transcode-redis-srv:6379"
          resources:
            requests:
              cpu: "1000m"
              memory: "1Gi"
            limits:
              cpu: "2000m"
              memory: "2Gi"
          volumeMounts:
            - name: input-volume
              mountPath: /app/src/movies
            - name: output-volume
              mountPath: /app/src/output
      volumes:
        - name: input-volume
          persistentVolumeClaim:
            claimName: movies-input-pvc
        - name: output-volume
          persistentVolumeClaim:
            claimName: movies-output-pvc