apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-login-activity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-login-activity
  template:
    metadata:
      labels:
        app: user-login-activity
    spec:
      initContainers:
        - name: wait-for-nats
          image: busybox
          command: ["sh", "-c", "until nc -z nats-srv:4222; do sleep 1; done"]
      containers:
        - name: user-login-activity
          image: stile95/user-login-activity
          env:
            - name: DATABASE_URL
              value: "mongodb://user-login-activity-mongo-srv:27017/user-login-activity"
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: JWT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: user-login-activity-srv
spec: ##default ClusterIP service
  selector:
    app: user-login-activity
  ports:
    - name: user-login-activity
      protocol: TCP
      port: 3000
      targetPort: 3000
