apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-login-activity-mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-login-activity-mongo
  template:
    metadata:
      labels:
        app: user-login-activity-mongo
    spec:
      terminationGracePeriodSeconds: 60
      initContainers:
        - name: remove-lockfile
          image: busybox
          command: ["sh", "-c", "rm -f /data/db/mongod.lock /data/db/WiredTiger.lock"]
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 999:999 /data/db && chmod -R u+rwX /data/db"]
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      containers:
        - image: mongo
          name: user-login-activity-mongo
          lifecycle:
            preStop:
              exec:
                command: ["mongod", "--dbpath", "/data/db", "--shutdown"]
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: user-login-activity-mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: user-login-activity-mongo-srv
spec:
  selector:
    app: user-login-activity-mongo
  ports:
    - name: mongodb
      protocol: TCP
      port: 27017
      targetPort: 27017