apiVersion: v1
kind: PersistentVolume
metadata:
  name: watch-history-mongo-pv
  labels:
    app: watch-history-mongo
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/watch-history-mongo-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: watch-history-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  selector:
    matchLabels:
      app: watch-history-mongo