apiVersion: apps/v1
kind: Deployment
metadata:
  name: watch-history-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watch-history
  template:
    metadata:
      labels:
        app: watch-history
    spec:
      initContainers:
        - name: wait-for-nats
          image: busybox
          command: ["sh", "-c", "until nc -z nats-srv:4222; do sleep 1; done"]
        - name: wait-for-mongo
          image: busybox
          command: ["sh", "-c", "until nc -z watch-history-mongo-srv:27017; do sleep 1; done"] 
      containers:
        - name: watch-history
          image: stile95/watch-history
          env:
            - name: DATABASE_URL
              value: "mongodb://watch-history-mongo-srv:27017/watch-history"
            - name: JWT_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET_KEY
            - name: NATS_URL
              value: "http://nats-srv:4222"
---
apiVersion: v1
kind: Service
metadata:
  name: watch-history-srv
spec: ##default ClusterIP service
  selector:
    app: watch-history
  ports:
    - name: watch-history
      protocol: TCP
      port: 3000
      targetPort: 3000
